### ISSUE TITLE
Undefined Query Args Cause The Tools To Crash

### ISSUE THREAD

**Issue by sporieg** [FormidableLabs/urql-devtools#181]
I created a PR to fix it, but I maybe I should have created the issue first.  #180

Details copied here:

I have a query with an optional input variable, like

```graphsl
query aQuery(
  $tenant: [String!]!
  $input: Input!
  $after: String
) {
```

This results in the tab crashing after that query is executed in my app.

```
Main._createAppUI: 18.40673828125ms
MainImpl.js:5 Main._showAppUI: 7.31396484375ms
MainImpl.js:5 Main._initializeTarget: 7.925048828125ms
MainImpl.js:5 Main._lateInitialization: 3.051025390625ms
panel.js:2 TypeError: Cannot read property 'length' of undefined
    at Object.matchGrammar (panel.js:2)
    at Object.tokenize (panel.js:2)
    at t.render (panel.js:2)
    at Do (panel.js:2)
    at jo (panel.js:2)
    at vc (panel.js:2)
    at sl (panel.js:2)
    at cl (panel.js:2)
    at Jc (panel.js:2)
    at panel.js:2
chrome-extension://m…el.html#/explorer:1 Error in event handler: TypeError: Cannot read property 'length' of undefined
    at Object.matchGrammar (chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:2:1616658)
    at Object.tokenize (chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:2:1617438)
    at t.render (chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:2:1678169)
    at Do (chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:2:1321152)
    at jo (chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:2:1320947)
    at vc (chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:2:1356746)
    at sl (chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:2:1347993)
    at cl (chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:2:1347918)
    at Jc (chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:2:1344948)
    at chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:2:1296590
chrome-extension://m…el.html#/explorer:1 Error in event handler: TypeError: Cannot read property 'length' of undefined
    at Object.matchGrammar (chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:2:1616658)
    at Object.tokenize (chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:2:1617438)
    at t.render (chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:2:1678169)
    at Do (chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:2:1321152)
    at jo (chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:2:1320947)
    at vc (chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:2:1356746)
    at sl (chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:2:1347993)
    at cl (chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:2:1347918)
    at Jc (chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:2:1344948)
    at chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:2:1296590
```

![image](https://user-images.githubusercontent.com/5818899/80738132-c3714600-8ad1-11ea-8a7c-181f265a7247.png)

The root cause is `JSON.stringify` has a bad type definition.  It will return undefined for an undefined input.  So when it tries to render the `$after` variable, it crashes.

**Comment by andyrichardson** [comment]
Hey @sporieg, thanks for the detailed issue report (and the PR - really appreciate it!).

I'll spend some time today looking over this and will get back to you!

**Comment by andyrichardson** [comment]
Fixed by #180

**Comment by sporieg** [comment]
@andyrichardson 

Thanks, and glad to help.  The tools are very useful.

 I am wondering if we can get an updated release?
While we can work around by running a locally built release in dev mode, I would like if we could all get back on the store version.

**Comment by andyrichardson** [comment]
@sporieg Sorry about the hold up, we're still getting to grips with some things - there's going to be another major release some time this week (another, I know) to add support for react native so keep your eyes peeled.

The review process can take a couple of days but we're hoping it'll be on the chrome store by Monday and the Firefox store by tomorrow.

**Comment by andyrichardson** [comment]
@sporieg if you're using Firefox, this is now live - just be sure to update your `@urql/devtools` package. For chrome, you'll want to hold off the package update until this release has been approved by the Chrome Store team.

Thanks again for your contribution for this release 🚀
