### ISSUE TITLE
[Runtime error]: React invariant on schema explorer

### ISSUE THREAD

**Issue by jellydn** [FormidableLabs/urql-devtools#311]
## About
A runtime error occurred.

## Stack trace

```
Error: Minified React error #310; visit https://reactjs.org/docs/error-decoder.html?invariant=310 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Jo (chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:2:1041739)
    at Object.fa [as useCallback] (chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:2:1044542)
    at t.useCallback (chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:2:982667)
    at El (chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:8:89430)
    at qo (chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:2:1041137)
    at Ma (chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:2:1049998)
    at gs (chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:2:1088595)
    at cu (chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:2:1079924)
    at su (chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:2:1079849)
    at Zs (chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:2:1076879)
```

**Comment by andyrichardson** [comment]
@jellydn thanks for the report.

Are you able to give any information as to when/how this occurred? 

Reproduction steps are the first requirement in order to start looking into a fix.

**Comment by jellydn** [comment]
Thanks. Good to know that you've already found the reproduce steps.
