### ISSUE TITLE
[Runtime error]: Cannot convert object to primitive value

### ISSUE THREAD

**Issue by rem4ik4ever** [FormidableLabs/urql-devtools#329]
## About
A runtime error occurred.

## Stack trace

```
TypeError: Cannot convert object to primitive value
    at o (chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:8:77853)
    at chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:8:78576
    at Array.map (<anonymous>)
    at chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:8:78373
    at Array.map (<anonymous>)
    at Uc (chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:8:78068)
    at qo (chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:2:1041137)
    at gs (chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:2:1087376)
    at cu (chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:2:1079924)
    at su (chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:2:1079849)
```

**Comment by andyrichardson** [comment]
Hey thanks for this report - I've a strong suspicion this is related to the new major update of Urql.

What version of Urql are you using?

**Comment by rem4ik4ever** [comment]
Hey @andyrichardson .

I use `urql: 1.11.6`

**Comment by bartenra** [comment]
Same issue with `@urql/vue 0.3.0` which uses `"@urql/core" 2.0.0`.

**Comment by andyrichardson** [comment]
Apologies I haven't gotten around to looking at this - I'm going to close this in favor of #323
