### ISSUE TITLE
[Runtime error]: Add support for Urql 2

### ISSUE THREAD

**Issue by danbeneventano** [FormidableLabs/urql-devtools#330]
## About
None of my queries are showing up, and I'm getting this error when I go to the "Events" tab

## Stack trace

```
TypeError: Cannot read property '0' of undefined
    at chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:8:38140
    at ht (chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:2:1200793)
    at e.generateAndInjectStyles (chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:2:1202428)
    at chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:2:1203759
    at jt (chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:2:1203826)
    at TimelineSourceIcon (chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:2:1204939)
    at qo (chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:2:1041137)
    at Ia (chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:2:1049093)
    at gs (chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:2:1089624)
    at cu (chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:2:1079924)
```

**Comment by andyrichardson** [comment]
Hey thanks for this report - I've a strong suspicion this is related to the new major update of Urql.

What version of Urql are you using?

**Comment by danbeneventano** [comment]
2.0.1 @andyrichardson

**Comment by andyrichardson** [comment]
Sounds about right - make sure you're on the latest version of @urql/devtools and your browser should update to the latest extension release soon 👍

If you're on Firefox, the fix is already out

**Comment by Undistraction** [comment]
@andyrichardson I've just installed the Firefox extension and I get nothing in any of the tabs.

**Comment by andyrichardson** [comment]
@Undistraction thanks for the report - that is an unrelated issue and a fix was just published (see #335 and [v2.4.2](https://github.com/FormidableLabs/urql-devtools/releases/tag/v2.4.2))

**Comment by andyrichardson** [comment]
Quick update, there is new criteria on the chrome store that needed to be filled out prior to any new releases.

This is done and we're pending review.

![Screen Shot 2021-02-18 at 13 35 55](https://user-images.githubusercontent.com/10779424/108365013-a0de2400-71ee-11eb-9368-ac445ca9b42d.png)

Just a heads up, with the Chrome Web Store, reviews can take anything from a few hours to weeks.

**Comment by Undistraction** [comment]
@andyrichardson thanks for the update.

**Comment by andyrichardson** [comment]
2.4.2 is live!

Thanks everyone for your patience

**Comment by Undistraction** [comment]
@andyrichardson This is working for me. Thanks again.
