### ISSUE TITLE
[Runtime error]: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by packetstracer** [FormidableLabs/urql-devtools#333]
## About
A runtime error occurred.

## Reproduction

Open the Devtools
Access the urql tab
Access the events urql tab

## Additional info

Browser: Version 88.0.4324.150 (Official Build) snap (64-bit)
OS: 20.04.1-Ubuntu

## Stack trace

```
TypeError: Cannot read property '0' of undefined
    at chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:8:38140
    at ht (chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:2:1200793)
    at e.generateAndInjectStyles (chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:2:1202428)
    at chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:2:1203759
    at jt (chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:2:1203826)
    at TimelineSourceIcon (chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:2:1204939)
    at qo (chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:2:1041137)
    at Ia (chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:2:1049093)
    at gs (chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:2:1089624)
    at cu (chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:2:1079924)
```

**Comment by andyrichardson** [comment]
Thanks for the report - I'm going to close this in favor of #330
