### ISSUE TITLE
[Runtime error]: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.

### ISSUE THREAD

**Issue by Hypermona** [FormidableLabs/urql-devtools#374]
# About

  

  Devtools does not detect a running instance of urql.

  # Reproduction

  

  1.  Clone [this example](https://github.com/FormidableLabs/urql/tree/main/packages/react-urql/examples/1-getting-started) project
  2.  Run `yarn install`
  3.  Run `yarn start`
  4.  Open chrome and navigate to [http://localhost:8080](http://localhost:8080)
  5.  Open the urql devtools panel

  ## Expected result

  

  - Extension detects app

  ## Actual result

  

  - Extension shows message "Waiting for exchange"

  ## Stack trace

  ```
  Error: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at la (chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:6:58506)
    at Qo (chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:2:1043871)
    at ws (chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:2:1089921)
    at yu (chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:2:1082663)
    at mu (chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:2:1082588)
    at su (chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:2:1079618)
    at chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:2:1031259
    at t.unstable_runWithPriority (chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:2:1106315)
    at Gi (chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:2:1030968)
    at Ji (chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:2:1031204)
  ```

  # Additional info

  | environment    | version   |
  | -------------- | --------- |
  | browser        | Chrome 69 |
  | urql           | 0.0.0     |
  | urql devtools  | 0.0.0     |
  | @urql/devtools | 0.0.0     |

**Comment by andyrichardson** [comment]
Hey there, thanks for the report!

Looks like this issue is caused by https://github.com/FormidableLabs/urql-devtools/pull/350.

@ValGeorgiev was local storage working for you in the browser extension?

**Comment by frederikhors** [comment]
Is there a work-around?

**Comment by andyrichardson** [comment]
HI @frederikhors, for now there isn't - I just tried to reproduce the issue but haven't had any luck.

I'm guessing this is related to the browser being used - would be great if yourself or @Hypermona can share what browser and version you're experiencing this on.

**Comment by frederikhors** [comment]
Chrome 94 Windows 10.

**Comment by raduflp** [comment]
It can be reproduced in Chrome 93, but only in Incognito Mode.
Tried disabling "Privacy Sandbox" but to no avail.

**Comment by frederikhors** [comment]
@andyrichardson Is anyone expected to work on it?

**Comment by pantajoe** [comment]
Had the same issue.
After deactivating "Block third-party cookies", the extension works (I believe you can also add an exception for localhost instead of disabling this option for all sites). Tested on MacOS and Chrome 99:
![image](https://user-images.githubusercontent.com/31014018/159124555-dd5fad5c-77a1-49b8-abc1-29f0bf261c51.png)

**Comment by andyrichardson** [comment]
Hey folks, sounds like this is due to having third party cookies blocked as @pantajoe has discovered - enabling them for the time being should get around the issue.

I'll leave this open as this can likely be resolved by introducing a check to see whether `localStorage` is available ([see here](https://github.com/FormidableLabs/urql-devtools/commit/693a72e9bbf7e0edf4ef92ae1c2963b9c8ee7a02)) before storing cross-session state.

**Comment by peter-olom** [comment]
Will this ever be fixed? This issue appears stale and still a problem in 2023
