### ISSUE TITLE
[Runtime error]: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.

### ISSUE THREAD

**Issue by angelozdev** [FormidableLabs/urql-devtools#394]
# About

  

  Devtools does not detect a running instance of urql.

  # Reproduction

  

  1.  Clone [this example](https://github.com/FormidableLabs/urql/tree/main/packages/react-urql/examples/1-getting-started) project
  2.  Run `yarn install`
  3.  Run `yarn start`
  4.  Open chrome and navigate to [http://localhost:8080](http://localhost:8080)
  5.  Open the urql devtools panel

  ## Expected result

  

  - Extension detects app

  ## Actual result

  

  - Extension shows message "Waiting for exchange"

  ## Stack trace

  ```
  Error: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at la (chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:6:58506)
    at Qo (chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:2:1044168)
    at Cs (chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:2:1090218)
    at yu (chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:2:1082960)
    at mu (chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:2:1082885)
    at su (chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:2:1079915)
    at chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:2:1031556
    at t.unstable_runWithPriority (chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:2:1106612)
    at Gi (chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:2:1031265)
    at Ji (chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:2:1031501)
  ```

  # Additional info

  | environment    | version   |
  | -------------- | --------- |
  | browser        | Chrome 69 |
  | urql           | 0.0.0     |
  | urql devtools  | 0.0.0     |
  | @urql/devtools | 0.0.0     |

**Comment by andyrichardson** [comment]
Thanks for the report, there's more info about how to get around this here https://github.com/FormidableLabs/urql-devtools/issues/374
